{% set version = "1.5.0-5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-zcompositions
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/zCompositions_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/zCompositions/zCompositions_{{ version }}.tar.gz
  sha256: a5e71c878ae1c8141851a456fee5aaebc83a19654bb4aef9cf7b92ef6799981f

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-nada
    - r-truncnorm
  run:
    - r-base
    - r-mass
    - r-nada
    - r-truncnorm

test:
  commands:
    - $R -e "library('zCompositions')"           # [not win]
    - "\"%R%\" -e \"library('zCompositions')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=zCompositions
  license: GPL-2.0-or-later
  summary: Principled methods for the imputation of zeros, left-censored and missing data in compositional data sets.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: zCompositions
# Type: Package
# Title: Treatment of Zeros, Left-Censored and Missing Values in Compositional Data Sets
# Version: 1.3.2-1
# Date: 2019-07-02
# Author: Javier Palarea-Albaladejo and Josep Antoni Martin-Fernandez
# Maintainer: Javier Palarea-Albaladejo <javier.palarea@bioss.ac.uk>
# Depends: R (>= 2.14.0), MASS, NADA, truncnorm
# ByteCompile: yes
# Description: Principled methods for the imputation of zeros, left-censored and missing data in compositional data sets.
# License: GPL (>= 2)
# Repository: CRAN
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2019-07-02 15:43:01 UTC; Japal
# Date/Publication: 2019-07-03 05:10:03 UTC
