{% set version = '1.3.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-zcompositions
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/zCompositions_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/zCompositions/zCompositions_{{ version }}.tar.gz
  sha256: 3676b47b1435be1827f375f5dbc2a7bbf3d3c640fc8c4eba467f2e1d9b94f6d4

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-nada
    - r-miscf
    - r-truncnorm
  run:
    - r-base
    - r-mass
    - r-nada
    - r-miscf
    - r-truncnorm

test:
  commands:
    - $R -e "library('zCompositions')"           # [not win]
    - "\"%R%\" -e \"library('zCompositions')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=zCompositions
  license: GPL (>= 2)
  summary: Principled methods for the imputation of zeros, left-censored and missing data in
    compositional data sets.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: zCompositions
# Type: Package
# Title: Treatment of Zeros, Left-Censored and Missing Values in Compositional Data Sets
# Version: 1.3.2
# Date: 2019-09-01
# Author: Javier Palarea-Albaladejo and Josep Antoni Martin-Fernandez
# Maintainer: Javier Palarea-Albaladejo <javier.palarea@bioss.ac.uk>
# Depends: R (>= 2.14.0), MASS, NADA, truncnorm, miscF
# ByteCompile: yes
# Description: Principled methods for the imputation of zeros, left-censored and missing data in compositional data sets.
# License: GPL (>= 2)
# Repository: CRAN
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2019-06-01 07:18:21 UTC; Japal
# Date/Publication: 2019-06-02 05:20:04 UTC
